spring:
  main:
    web-application-type: none
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
