spring:
  sql:
    init:
      mode: always
  main:
    web-application-type: none
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
